name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: "${{ secrets.GLADOS_COOKIE }}"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
#      - uses: gautamkrishnar/keepalive-workflow@master
      - name: Run ikuuu
        run: |
          python3 ikuuu.py
        env:
          ikuuu_COOKIE: "${{ secrets.ikuuu_COOKIE }}"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          IKUUU_KEY : ${{ secrets.IKUUU_KEY }}
          IKUUU_EMAIL : ${{ secrets.IKUUU_EMAIL }}
          IKUUU_PWD : ${{ secrets.IKUUU_PWD }}
      # - uses: gautamkrishnar/keepalive-workflow@master
      - name: Commitfile
        if: github.event.schedule == '30 1 * * *'
        run: |
          git config --global user.email ${{ secrets.GITH_EMAIL }}
          git config --global user.name Mmingdev
          git add .
          git commit -m "记录日志"

      - name: Push changes
        if: github.event.schedule == '30 1 * * *'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITH_TOKEN }}
